# Site
name: "Pedestal"
title: "Pedestal"
description: "Your Voice Does Make a Difference"
meta_description: "Your Voice Does Make a Difference"
logo: 'assets/images/logo.png'
favicon: 'assets/images/fevicon.png'
paginate: 12
baseurl: '/'
email: 'info.pedestalofficial@gmail.com'
google_analytics: ''
disqus: ''
sharethis: ''

# Authors
authors:
  mrigank:
    name: Mrigank Sinha
    display_name: Mrigank
  ambuj:
    name: Ambuj Sharma
    display_name: Ambuj
  aryaman:
    name: Aryaman Gupta
    display_name: Aryaman
  saumya:
    name: Saumya Katyal
    display_name: Saumya
  soham:
    name: Soham Banerjee
    display_name: Soham

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Other
markdown: kramdown
highlighter: rouge
